version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python test_main.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to the Production Server!!!"
      - run: sleep 30
      - run: echo "Deployment Completed for the Production Server!"

workflows:
  build_now:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master